name: flutter_CI

on:
  pull_request:
    branches:
      - dev
      - release
  push:
    branches:
      - dev
      - release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign
      - run: bash <(curl -s https://codecov.io/bash)
